version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./letsencrypt/etc:/etc/letsencrypt:ro
            - ./letsencrypt/html:/tmp/letsencrypt:ro
            - ../microraiden/microraiden/webui:/app/web/html:ro
            - ./files:/app/files:ro
            - ./files/tmp:/app/files/tmp
        links:
            - uwsgi
        logging:
            options:
                max-file: "1"
                max-size: "1g"
        environment:
            - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@

    uwsgi:
        build: ./uwsgi
        volumes:
            - ./uwsgi/app:/app:ro
            - ./files:/files
            - ./uwsgi/app.ini:/app.ini:ro
            - ../microraiden/microraiden/:/app/microraiden:ro
        logging:
            options:
                max-file: "1"
                max-size: "1g"
