version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./letsencrypt/etc:/etc/letsencrypt:ro
            - ./letsencrypt/html:/tmp/letsencrypt:ro
            - ./app/ng/dist:/app/ng/dist:ro
            - ./app/microraiden/webui:/app/web/html:ro
            - ./files:/app/files:ro
            - ./files/tmp:/app/files/tmp
            - ./files:/fileso
        links:
            - uwsgi
        logging:
            options:
                max-file: "1"
                max-size: "1g"
        environment:
            - LE_RENEW_HOOK=docker kill -s HUP @CONTAINER_NAME@

    uwsgi:
        build: .
        volumes:
            - ./app:/app:ro
            - ./files:/files
            - ./app.ini:/app.ini:ro
#         links:
#             - postgres
        logging:
            options:
                max-file: "1"
                max-size: "1g"

#    postgres:
#        image: postgres:9.6
#        environment:
#            - POSTGRES_PASSWORD=8EnzgALl
#        volumes:
#            - ./db/9.6:/var/lib/postgresql/data
#        ports:
#            - "127.0.0.1:5432:5432"
#
#    letsencrypt:
#        image: kvaps/letsencrypt-webroot
#        volumes:
#            - ./letsencrypt/etc:/etc/letsencrypt
#            - ./letsencrypt/html:/tmp/letsencrypt
#            - /var/run/docker.sock:/var/run/docker.sock
#        links:
#            - nginx
#        environment:
#            - DOMAINS=vault.linksolutions.co
#            - EMAIL=andre.vmatos@gmail.com
#            - WEBROOT_PATH=/tmp/letsencrypt
#            - EXP_LIMIT=30
#            - CHECK_FREQ=1
#
